version: '3'
services:
  audit:
    image: node:10
    ports:
      - "${AUDIT_PORT:-3004}:3004"
    working_dir: "/src"
    healthcheck:
      test: "curl localhost:3004/health"
      interval: 1m
      timeout: 10s
      retries: 3
    command: ["bash", "-c", "yarn && yarn run start:dev"]
    volumes:
      - ./:/src/:z
      - ./config/:/etc/reviewer/:z
    networks:
      - "infra_rabbit"

networks:
  infra_rabbit:
    external:
      name: "infra_rabbit"