version: '3'
services:
  audit:
    image: liberoadmin/audit:latest
    container_name: test_audit
    ports:
      - "${AUDIT_PORT:-3004}:3004"
    environment:
      CONFIG_PATH: ./tests/config.json
    healthcheck:
      test: "curl localhost:3004/health"
      interval: 2s
      timeout: 30s
      retries: 10
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: test_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 2s
      timeout: 30s
      retries: 10

  postgres:
    image: postgres:11
    container_name: test_postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10
